### ISSUE TITLE
Additional PHI to be removed from twix headers

### ISSUE THREAD

**Issue by josephmje** [bennyrowland/suspect#8]
Hi Ben,

The twix headers also contain PatientWeight, PatientAge and PatientTelephoneNumber fields that might also need to be anonymized. 

Also, I was wondering if you know whether any PHI are held outside of the twix headers in the binary data?

Thanks,
Michael

**Comment by bennyrowland** [comment]
Hi Michael,

I am going to move this issue to the OpenMRSLab repo which is where ongoing development is taking place, and will look into anonymising these fields.

I can confirm that the binary data only contains the scan parameters and the raw ADC data, according to the specification that I have seen.

Ben

**Comment by josephmje** [comment]
Thanks Ben,

Sorry, I was wrong about the PatientTelephoneNumber field. I thought I saw it somewhere but I must have been working with another file type. 

Nucgaek
